[package]
edition = "2021"
name = "tng-testsuite"
version = "0.0.1"

[dependencies]
again = "0.1.2"
anyhow = "1.0.95"
async-http-proxy = {version = "1.2.5", features = ["runtime-tokio"]}
async-trait = "0.1.86"
axum = "0.8.1"
axum-extra = "0.10.0"
ctor = "=0.4.1"
futures = "0.3.31"
http = "1.2.0"
netns-rs = "0.1.0"
opentelemetry-stdout = "0.29.0"
rand = "0.9.0"
reqwest = {version = "0.12.12", default-features = false, features = ["json", "h2", "rustls-tls-webpki-roots"]}
rtnetlink = "0.16.0"
rustls = {version = "0.23.27", default-features = false, features = ["logging", "std", "tls12", "ring", "brotli"]}
serde_json = "1.0.138"
tng = {path = "../tng"}
tokio = {version = "1.43.0", features = ["rt-multi-thread", "sync"]}
tokio-util = "0.7.13"
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
