[package]
edition = "2021"
name = "tng"
version = "1.0.4"

[dependencies]
anyhow = "1.0.81"
auto_enums = {version = "0.8", features = ["tokio1"]}
axum = "0.7.5"
bytes = "1.10.0"
clap = {version = "4.5.4", features = ["derive"]}
ctrlc = {version = "3.4.4", features = ["termination"]}
futures = "0.3.31"
h2 = {version = "0.4.7", features = ["stream"]}
http = "1.1.0"
http-body-util = "0.1.2"
hyper = {version = "1", features = ["full"]}
hyper-rustls = {version = "0.27.3", features = ["http2"]}
hyper-util = {version = "0.1.8", features = ["service"]}
itertools = "0.13.0"
log = "0.4.20"
nix = {version = "0.29.0", features = ["process", "signal"]}
pin-project = "1"
rand = "0.8.5"
rats-cert = {path = "./deps/rats-rs/rats-cert", default-features = false, features = ["coco", "crypto-rustcrypto"]}
regex = "1.11.0"
rustls = "0.23.13"
rustls-pemfile = "2.1.3"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.89"
serde_with = {version = "3.11.0", features = ["json"]}
shadow-rs = "=0.20.1"
tempfile = "3.10.1"
tokio = {version = "1.40.0", features = ["rt-multi-thread", "sync"]}
tokio-rustls = "0.26.0"
tower = {version = "0.4", features = ["make", "util"]}
tower-http = {version = "0.6.1", features = ["trace", "set-header"]}
tracing = "0.1"
tracing-log = "0.2.0"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
which = "6.0.3"

[build-dependencies]
shadow-rs = "=0.20.1"

[dev-dependencies]
again = "0.1.2"
async-http-proxy = {version = "1.2.5", features = ["runtime-tokio"]}
axum = "0.7.7"
console-subscriber = "0.4.1"
futures = "0.3.31"
http = "1.1.0"
reqwest = {version = "0.12.9", default-features = false, features = ["json"]}
tokio = {version = "1.41.1", features = ["full"]}
tokio-util = "0.7.12"
