[package]
edition = "2021"
name = "tng"
version = "2.0.0"

[dependencies]
again = "0.1.2"
anyhow = "1.0.95"
async-trait = "0.1.86"
auto_enums = {version = "0.8", features = ["tokio1"]}
axum = "0.8.1"
bytes = "1.10.0"
clap = {version = "4.5.28", features = ["derive"]}
const_format = "0.2.34"
ctrlc = {version = "3.4.5", features = ["termination"]}
derivative = "2.2.0"
either = "1.15.0"
futures = "0.3.31"
h2 = {version = "0.4.7", features = ["stream"]}
http = "1.2.0"
http-body-util = "0.1.2"
hyper = {version = "1", features = ["full"]}
hyper-rustls = {version = "0.27.5", default-features = false, features = ["http1", "logging", "native-tokio", "tls12", "ring", "http2"]}
hyper-util = {version = "0.1.10", features = ["service"]}
indexmap = {version = "2.8.0", features = ["serde"]}
itertools = "0.14.0"
nix = {version = "0.29.0", features = ["process", "signal", "socket", "net"]}
opentelemetry = "0.29.1"
opentelemetry_sdk = "0.29.0"
pin-project = "1"
portpicker = "0.1.1"
rand = "0.9.0"
rats-cert = {path = "./deps/rats-rs/rats-cert", default-features = false, features = ["coco", "crypto-rustcrypto"]}
regex = "1.11.1"
reqwest = {version = "0.12.12", default-features = false, features = ["json", "h2", "rustls-tls-webpki-roots"]}
rustls = {version = "0.23.22", default-features = false, features = ["logging", "std", "tls12", "ring"]}
rustls-pemfile = "2.2.0"
scopeguard = "1.2.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.138"
serde_variant = "0.1.3"
serde_with = {version = "3.12.0", features = ["json"]}
shadow-rs = {version = "1.0.0", default-features = false}
socket2 = "0.5.8"
strum = "0.27.1"
strum_macros = "0.27.1"
tempfile = "3.16.0"
tokio = {version = "1.43.0", features = ["rt-multi-thread", "sync"]}
tokio-graceful = "0.2.2"
tokio-rustls = {version = "0.26.1", default-features = false, features = ["logging", "tls12", "ring"]}
tokio-util = "0.7.13"
tower = {version = "0.5", features = ["make", "util"]}
tower-http = {version = "0.6.2", features = ["trace", "set-header"]}
tracing = "0.1"
tracing-log = "0.2.0"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}
which = "7.0.2"

[build-dependencies]
shadow-rs = {version = "1.0.0", default-features = false, features = ["tzdb", "build"]}

[dev-dependencies]
async-http-proxy = {version = "1.2.5", features = ["runtime-tokio"]}
axum-extra = "0.10.0"
console-subscriber = "0.4.1"
ctor = "=0.4.1"
opentelemetry-stdout = "0.29.0"
