[workspace]
default-members = ["tng"]
exclude = ["deps/"]
members = ["tng", "tng-testsuite"]
resolver = "2"

[patch.crates-io]
rustls = {git = "https://github.com/inclavare-containers/rustls.git", branch = "v/0.23.27-patched"}
rustls-webpki = {git = "https://github.com/inclavare-containers/webpki.git", branch = "v/0.103.3-patched"}
